"""Pure-memory regressions for controls first generated by the trusted hook."""
from __future__ import annotations

from copy import deepcopy
from types import SimpleNamespace

import pytest

from plugins.life_engine.core.context_stewardship import (
    build_compression_required_payload,
    has_compression_required_payload,
    install_subject_context_recovery_hook,
    is_compression_required_part,
)
from plugins.life_engine.service.heartbeat_rolling import copy_rolling_payloads, snapshot_dict
from src.kernel.llm import LLMPayload, ROLE, Text
from src.kernel.llm.context import LLMContextManager
from src.kernel.llm.exceptions import LLMContextError, LLMTimeoutError
from src.kernel.llm.policy import create_policy
from src.kernel.llm.request import LLMRequest
from src.kernel.llm.response import LLMResponse


WAKE = "[synthetic-exact-wake]\n" + "W" * 500


def _cost(payloads):
    return sum(len(part.text) for payload in payloads for part in payload.content
               if isinstance(part, Text))


def _payloads(old="old " * 2000):
    return [
        LLMPayload(ROLE.SYSTEM, Text("synthetic system")),
        LLMPayload(ROLE.USER, Text(old)),
        LLMPayload(ROLE.ASSISTANT, Text("synthetic old response")),
        LLMPayload(ROLE.USER, Text(WAKE)),
    ]


def _manager(*, opted_in=True):
    manager = LLMContextManager(
        protected_exact_texts=frozenset({WAKE}) if opted_in else frozenset(),
    )
    install_subject_context_recovery_hook(SimpleNamespace(context_manager=manager))
    return manager


def _controls(payloads):
    return [part.text for payload in payloads if payload.role == ROLE.USER
            for part in payload.content if is_compression_required_part(part)]


def test_new_control_that_cannot_fit_fails_without_clipping_or_original_mutation():
    manager = _manager()
    payloads = _payloads()
    before = snapshot_dict(payloads)
    assert not has_compression_required_payload(payloads)
    with pytest.raises(LLMContextError, match="protected exact delivery text") as error:
        manager.maybe_trim(payloads, max_token_budget=1000, token_counter=_cost)
    assert WAKE not in str(error.value)
    assert snapshot_dict(payloads) == before


def test_new_control_is_registered_and_kept_exact_when_it_fits():
    manager = _manager()
    payloads = _payloads()
    before = snapshot_dict(payloads)
    result = manager.maybe_trim(payloads, max_token_budget=2500, token_counter=_cost)
    manager.validate_for_send(result)
    controls = _controls(result)
    assert len(controls) == 1
    assert controls[0] in manager.protected_exact_texts
    assert controls[0] in manager.reprojectable_exact_texts
    assert _cost(result) <= 2500
    assert any(part.text == WAKE for item in result for part in item.content if isinstance(part, Text))
    assert snapshot_dict(payloads) == before


def test_default_caller_does_not_implicitly_enable_exact_protection():
    manager = _manager(opted_in=False)
    result = manager.maybe_trim(_payloads(), max_token_budget=1000, token_counter=_cost)
    assert _cost(result) <= 1000
    assert manager.protected_exact_texts == frozenset()
    assert manager.reprojectable_exact_texts == frozenset()


def test_repeated_hook_calls_replace_owned_controls_without_accumulation():
    manager = _manager()
    first = manager.maybe_trim(_payloads("first " * 2000), max_token_budget=2500, token_counter=_cost)
    first_control = _controls(first)[0]
    second_input = _payloads("different " * 2000)
    before = snapshot_dict(second_input)
    second = manager.maybe_trim(second_input, max_token_budget=2500, token_counter=_cost)
    second_control = _controls(second)[0]
    assert second_control != first_control
    assert manager.protected_exact_texts == {WAKE, second_control}
    assert manager.reprojectable_exact_texts == {second_control}
    assert snapshot_dict(second_input) == before


def test_caller_reset_is_respected_and_does_not_resurrect_old_opt_in():
    manager = _manager()
    first = manager.maybe_trim(_payloads(), max_token_budget=2500, token_counter=_cost)
    assert _controls(first)[0] in manager.protected_exact_texts
    manager.protected_exact_texts = frozenset()
    manager.reprojectable_exact_texts = frozenset()
    result = manager.maybe_trim(_payloads("new " * 2000), max_token_budget=1000, token_counter=_cost)
    assert _cost(result) <= 1000
    assert not manager.protected_exact_texts
    assert not manager.reprojectable_exact_texts


def test_caller_reassignment_keeps_its_independently_protected_text():
    manager = _manager()
    first = manager.maybe_trim(_payloads(), max_token_budget=2500, token_counter=_cost)
    first_control = _controls(first)[0]
    manager.protected_exact_texts = frozenset({WAKE, first_control, "caller-owned"})
    manager.reprojectable_exact_texts = frozenset({first_control})
    second = manager.maybe_trim(_payloads("new " * 2000), max_token_budget=2500, token_counter=_cost)
    second_control = _controls(second)[0]
    assert manager.protected_exact_texts == {WAKE, first_control, second_control, "caller-owned"}
    assert manager.reprojectable_exact_texts == {first_control, second_control}


def test_two_phase_hook_invocations_preserve_one_control_and_wake():
    manager = _manager()
    payloads = [
        LLMPayload(ROLE.USER, Text("first old " * 2000)),
        LLMPayload(ROLE.ASSISTANT, Text("old reply")),
        LLMPayload(ROLE.USER, Text("second old " * 100)),
        LLMPayload(ROLE.ASSISTANT, Text("second reply")),
        LLMPayload(ROLE.USER, Text(WAKE)),
    ]
    notice = build_compression_required_payload(payloads)
    assert notice is not None
    budget = _cost([notice, payloads[-1]]) + 100
    calls = []
    original = manager.compression_hook
    def counted(dropped, remaining):
        calls.append(len(dropped))
        return original(dropped, remaining)
    manager.compression_hook = counted
    before = deepcopy(payloads)
    result = manager.maybe_trim(payloads, max_token_budget=budget, token_counter=_cost)
    assert len(calls) >= 2
    assert len(_controls(result)) == 1
    assert set(_controls(result)) <= manager.protected_exact_texts
    assert _cost(result) <= budget
    assert payloads == before


class _Client:
    def __init__(self):
        self.sent = []
        self.outcomes = []

    async def create(self, *, payloads, **_kwargs):
        self.sent.append(copy_rolling_payloads(payloads))
        outcome = self.outcomes.pop(0) if self.outcomes else ("synthetic response", None, None)
        if isinstance(outcome, BaseException):
            raise outcome
        return outcome


@pytest.fixture
def local_kernel(monkeypatch):
    client = _Client()
    registry = SimpleNamespace(get_client_for_model=lambda _model: client)
    monkeypatch.setattr("src.kernel.llm.request.get_default_model_client_registry", lambda: registry)
    monkeypatch.setattr("src.kernel.llm.request.record_trajectory", lambda *_args, **_kwargs: None)
    monkeypatch.setattr("src.kernel.llm.request.count_payload_tokens", lambda payloads, **_kwargs: _cost(payloads))
    monkeypatch.setattr(LLMResponse, "attach_to_inspector", lambda _self: None)
    return client


def _model(budget, identifier):
    return {
        "api_provider": "openai", "client_type": "openai",
        "model_identifier": identifier, "api_key": "synthetic-test-key",
        "base_url": "https://example.invalid", "max_context": 1000000,
        "max_tokens": 1, "context_tokens": budget, "max_retry": 0,
        "retry_interval": 0, "timeout": 2,
        "price_in": 0, "price_out": 0, "temperature": 0.7,
        "extra_params": {"context_reserve_ratio": 0, "context_reserve_tokens": 0},
    }


def _request(models):
    request = LLMRequest(
        models, "synthetic-generated-control", context_manager=_manager(),
        policy=create_policy("load_balanced"), enable_metrics=False,
    )
    request.payloads = _payloads()
    request.register_context_delivery(
        "synthetic-generated-delivery", WAKE, marker="[synthetic-exact-wake]",
    )
    return request


@pytest.mark.parametrize("fits", [True, False])
async def test_actual_first_attempt_keeps_new_control_or_fails_before_provider(local_kernel, fits):
    request = _request([_model(2500 if fits else 1000, "synthetic-first")])
    before = snapshot_dict(request.payloads)
    if fits:
        response = await request.send(stream=False)
        assert len(local_kernel.sent) == 1
        controls = _controls(local_kernel.sent[0])
        assert len(controls) == 1
        assert request.context_manager.protected_exact_texts == {WAKE, controls[0]}
        assert response.effective_context_receipt("synthetic-generated-delivery").exact_present
    else:
        with pytest.raises(LLMContextError, match="protected exact delivery text"):
            await request.send(stream=False)
        assert local_kernel.sent == []
    assert snapshot_dict(request.payloads) == before


@pytest.mark.parametrize("retry_fits", [True, False])
async def test_retry_budget_rechecks_new_control_without_accumulation(local_kernel, retry_fits):
    local_kernel.outcomes = [LLMTimeoutError("synthetic retry")]
    request = _request([
        _model(2500, "synthetic-first"),
        _model(2500 if retry_fits else 1000, "synthetic-second"),
    ])
    before = snapshot_dict(request.payloads)
    if retry_fits:
        response = await request.send(stream=False)
        assert len(local_kernel.sent) == 2
        assert response.effective_context_receipt("synthetic-generated-delivery").exact_present
        assert _controls(local_kernel.sent[0]) == _controls(local_kernel.sent[1])
    else:
        with pytest.raises(LLMContextError, match="protected exact delivery text"):
            await request.send(stream=False)
        assert len(local_kernel.sent) == 1
    controls = _controls(local_kernel.sent[0])
    assert len(controls) == 1
    assert request.context_manager.protected_exact_texts == {WAKE, controls[0]}
    assert request.context_manager.reprojectable_exact_texts == {controls[0]}
    assert snapshot_dict(request.payloads) == before
