"""API v1 公共 Pydantic schema。"""

from .auth import (
    CallerIdentity,
    LogoutResponse,
    SessionCreateRequest,
    SessionRefreshRequest,
    SessionResponse,
    WSTicketRequest,
    WSTicketResponse,
)
from .chat import (
    ChatMessage,
    ChatMessagePage,
    ChatPart,
    ChatReceipt,
    ChatReceiptList,
    ChatSender,
    ChatStreamPage,
    ChatStreamSummary,
)
from .commands import (
    CommandCancelResponse,
    CommandCreateRequest,
    CommandListResponse,
    CommandResponse,
    CommandStatusValue,
)
from .common import API_VERSION, SCHEMA_VERSION, StrictModel, VersionedModel, utc_now
from .error import ErrorBody, ErrorResponse, RecoveryHint
from .events import (
    EventActor,
    EventEnvelope,
    EventFilter,
    EventPage,
    EventReplyTarget,
    EventSource,
    EventSubscriptionValidateRequest,
    EventSubscriptionValidation,
    EventVisibility,
)
from .foundation import (
    AdapterStatus,
    BootstrapResponse,
    CapabilitiesResponse,
    CapabilityManifest,
    ComponentStatus,
    FeatureCapability,
    HealthResponse,
    OperationalState,
    ReadinessResponse,
)

__all__ = [
    "API_VERSION",
    "SCHEMA_VERSION",
    "AdapterStatus",
    "BootstrapResponse",
    "CallerIdentity",
    "CapabilitiesResponse",
    "CapabilityManifest",
    "ChatMessage",
    "ChatMessagePage",
    "ChatPart",
    "ChatReceipt",
    "ChatReceiptList",
    "ChatSender",
    "ChatStreamPage",
    "ChatStreamSummary",
    "CommandCancelResponse",
    "CommandCreateRequest",
    "CommandListResponse",
    "CommandResponse",
    "CommandStatusValue",
    "ComponentStatus",
    "ErrorBody",
    "ErrorResponse",
    "EventActor",
    "EventEnvelope",
    "EventFilter",
    "EventPage",
    "EventReplyTarget",
    "EventSource",
    "EventSubscriptionValidateRequest",
    "EventSubscriptionValidation",
    "EventVisibility",
    "FeatureCapability",
    "HealthResponse",
    "LogoutResponse",
    "OperationalState",
    "ReadinessResponse",
    "RecoveryHint",
    "SessionCreateRequest",
    "SessionRefreshRequest",
    "SessionResponse",
    "StrictModel",
    "VersionedModel",
    "WSTicketRequest",
    "WSTicketResponse",
    "utc_now",
]
